config/routes.rb
Rails.application.routes.draw do
  resources :home_appliances
  resources :headphones
  resources :laptops
  resources :televisions
  resources :cellphones
  root "home#index"

  get '/home/', to: 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cellphones = Cellphone.all
    @laptops = Laptop.all
    @televisions = Television.all
    @home_appliances = HomeAppliance.all
    @headphones = Headphone.all
  end
end

app/views/home/_footer.html.erb
<footer class="footer">
  <h6 class="text-capitalize text-light text-center my-0 bg-dark">For more detailed information about our products and deal contact us on the following social platforms</h6>
  <div class="container-fluid bg-dark">
    <div class="row d-flex justify-content-between mx-auto no-gutters py-3">
      <div class="col-2">
        <a href="https://wa.link/sqffd6">
          <i class="fab fa-whatsapp fa-2x text-light"></i>
        </a>
      </div>
      <div class="col-2">
        <i class="fab fa-instagram fa-2x text-light"></i>
      </div>
      <div class="col-2">
        <i class="fab fa-twitter fa-2x text-light"></i>
      </div>
      <div class="col-2">
        <i class="fab fa-facebook fa-2x text-light"></i>
      </div>
    </div>
  </div>
  <div class="container-fluid bg-dark">
    <div class="row mx-auto">
      <div class="col-12 col-sm-4 col-md-4 mx-auto">
        <p class="text-white">&copy;2021 TRIPPLE STARS&trade; electronics all rigths reserved</p>
      </div>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <%= link_to "Televisions", televisions_path, class:"navbar-brand col-1" %>
    <%= link_to "Home", home_path, class:"navbar-brand col-1" %>
    <%= link_to "Cellphones", cellphones_path, class:"navbar-brand col-1" %>
    <%= link_to "Headphones", headphones_path, class:"navbar-brand col-2" %>
    <%= link_to "Laptops", laptops_path, class:"navbar-brand col-1" %>
    <%= link_to "Home Appliances", home_appliances_path, class:"navbar-brand col-3" %>
    <div class="collapse navbar-collapse col-2" id="navbarSupportedContent">
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


<section class="d-none d-md-block cl">
  <div class="container py-3 mb-3">
    <div class="row">
      <div class="col text-white d-flex flex-column align-items-center">
        <h1 class="display-3">TRIPPLE STARS&reg;</h1>
        <p class="text-capitalize display-5">inspired to change your future</p>
      </div>
    </div>
    <div class="row no-gutters">
      <form action="get" class="col-12 d-flex">
        <input type="text" name="categories" class="col-3 text-center" placeholder="All categories" id="cat">
        <input type="text" name="quest" class="col-4 mx-1 text-center" placeholder="What are you searching for?" id="quest">
        <input type="text" name="quest" class="col-4 mx-1 text-center" placeholder="Country or Region" id="quet">
        <input type="submit" class="col-1 bg-secondary text-light" value="Search">
      </form>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<div class="row mt-2">
  <h5>Showing <%= pluralize(@televisions.length, "result")%> of televisions</h5>
  <% @televisions.each do |television| %>
    <div class="card col-3 mx-auto mb-2">
      <img src="<%= television.image %>">
      <div class="card-body">
        <p>
          <%= television.brandname %>
        </p>
        <p>
          <%= television.description %>
        </p>
        <p class="text-danger">
          <%= television.condition %>
        </p>
        <p>
          <%= television.location %>
        </p>
        <p class="text-danger">
          <%= television.price %>
        </p>
      </div>
      <div class="card-footer d-flex justify-content-between">
        <div class="col-3">
          <%= link_to 'Show', television, class:"btn btn-outline-success py-0 px-1" %>
        </div>
        <div class="col-3">
          <%= link_to 'Edit', edit_television_path(television), class:"btn btn-outline-success py-0 px-1" %>
        </div>
        <div class="col-3">
          <%= link_to 'Delete', television, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger py-0 px-1" %>
        </div>
      </div>
    </div>
  <% end %>
</div>








<div class="row my-5">
  <% @cellphones.each do |cellphone| %>
  <div class="card col-3 mx-auto bg-light">
    <img src="<%= cellphone.image %>" class="w-100 h-50 bg-white">
    <div class="card-body">
      <p>
        <%= cellphone.brandname %>
      </p>
      <p class="card-text">
        <%= cellphone.color %>
      </p>
      <p class="card-text">
        <%= cellphone.memory %>
      </p>
      <p class="card-text">
        <%= cellphone.description %>
      </p>
      <p class="card-text text-danger">
        <%= cellphone.condition %>
      </p>
      <p class="card-text">
        <%= cellphone.location.upcase %>
      </p>
      <p class="card-text">
        <%= cellphone.price %>
      </p>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <div class="col-3">
        <%= link_to 'Show', cellphone, class:"btn btn-outline-success px-1 py-0" %>
      </div>
      <div class="col-3">
        <%= link_to 'Edit', edit_cellphone_path(cellphone), class:"btn btn-outline-success px-1 py-0" %>
      </div>
      <div class="col-3">
        <%= link_to 'Destroy', cellphone, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger px-1 py-0" %>
      </div>
    </div>
  </div>
  <% end %>
</div>








<div class="row my-3">
  <% @laptops.each do |laptop| %> 
  <div class="card col-3 mx-auto">
    <img src="<%= laptop.image %>">
    <div class="card-body">
      <p class="card-text">
        <%= laptop.brandname %>
      </p>
      <p class="card-text">
        <%= laptop.description %>
      </p>
      <p class="card-text text-danger">
        <%= laptop.condition %>
      </p>
      <p class="card-text">
        <%= laptop.location.upcase %>
      </p>
      <p class="card-text">
        <%= laptop.price %>
      </p>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <div class="col-3">
        <%= link_to 'Show', laptop, class:"btn btn-outline-success btn-sm" %>
      </div>
      <div class="col-3">
        <%= link_to 'Edit', edit_laptop_path(laptop), class:"btn btn-outline-success btn-sm" %>
      </div>
      <div class="col-3">
        <%= link_to 'Destroy', laptop, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %>
      </div>
    </div>
  </div>
  <% end %>
</div>







<div class="row my-3">
  <% @headphones.each do |headphone| %> 
  <div class="card col-3 mx-auto">
    <img src="<%= headphone.image %>">
    <div class="card-body">
      <p class="card-text">
        <%= headphone.brandname %>
      </p>
      <p class="card-text">
        <%= headphone.description %>
      </p>
      <p class="card-text text-danger">
        <%= headphone.condition %>
      </p>
      <p class="card-text">
        <%= headphone.location.upcase %>
      </p>
      <p class="card-text">
        <%= headphone.price %>
      </p>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <div class="col-3">
        <%= link_to 'Show', headphone, class:"btn btn-outline-success btn-sm" %>
      </div>
      <div class="col-3">
        <%= link_to 'Edit', edit_headphone_path(headphone), class:"btn btn-outline-success btn-sm" %>
      </div>
      <div class="col-3">
        <%= link_to 'Destroy', headphone, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %>
      </div>
    </div>
  </div>
  <% end %>
</div>






















<div class="row my-3">
  <% @home_appliances.each do |home_appliance| %> 
  <div class="card col-3 mx-auto">
    <img src="<%= home_appliance.image %>">
    <div class="card-body">
      <p class="card-text">
        <%= home_appliance.brandname %>
      </p>
      <p class="card-text">
        <%= home_appliance.description %>
      </p>
      <p class="card-text text-danger">
        <%= home_appliance.condition %>
      </p>
      <p class="card-text">
        <%= home_appliance.location.upcase %>
      </p>
      <p class="card-text">
        <%= home_appliance.price %>
      </p>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <div class="col-3">
        <%= link_to 'Show', home_appliance, class:"btn btn-outline-success btn-sm" %>
      </div>
      <div class="col-3">
        <%= link_to 'Edit', edit_home_appliance_path(home_appliance), class:"btn btn-outline-success btn-sm" %>
      </div>
      <div class="col-3">
        <%= link_to 'Destroy', home_appliance, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %>
      </div>
    </div>
  </div>
  <% end %>
</div>