config/routes.rb
Rails.application.routes.draw do
  resources :home_appliances
  resources :headphones
  resources :laptops
  resources :televisions
  resources :cellphones
  root "home#index"

  get '/home/', to: 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cellphone.rb
class Cellphone < ApplicationRecord
  mount_uploader :image, FileUploader
end

app/controllers/cellphones_controller.rb
class CellphonesController < ApplicationController
  before_action :set_cellphone, only: %i[ show edit update destroy ]

  # GET /cellphones or /cellphones.json
  def index
    @cellphones = Cellphone.all
  end

  # GET /cellphones/1 or /cellphones/1.json
  def show
  end

  # GET /cellphones/new
  def new
    @cellphone = Cellphone.new
  end

  # GET /cellphones/1/edit
  def edit
  end

  # POST /cellphones or /cellphones.json
  def create
    @cellphone = Cellphone.new(cellphone_params)

    respond_to do |format|
      if @cellphone.save
        format.html { redirect_to @cellphone, notice: "Cellphone was successfully created." }
        format.json { render :show, status: :created, location: @cellphone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cellphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cellphones/1 or /cellphones/1.json
  def update
    respond_to do |format|
      if @cellphone.update(cellphone_params)
        format.html { redirect_to @cellphone, notice: "Cellphone was successfully updated." }
        format.json { render :show, status: :ok, location: @cellphone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cellphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cellphones/1 or /cellphones/1.json
  def destroy
    @cellphone.destroy
    respond_to do |format|
      format.html { redirect_to cellphones_url, notice: "Cellphone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cellphone
      @cellphone = Cellphone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cellphone_params
      params.require(:cellphone).permit(:image, :brandname, :color, :memory, :description, :condition, :location, :price)
    end
end

app/helpers/cellphones_helper.rb
module CellphonesHelper
end

app/views/cellphones/_form.html.erb
<%= form_with(model: cellphone, local: true) do |form| %>
  <% if cellphone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cellphone.errors.count, "error") %> prohibited this cellphone from being saved:</h2>

      <ul>
        <% cellphone.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :brandname %>
    <%= form.text_field :brandname, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :memory %>
    <%= form.text_field :memory, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class="actions text-center">
    <%= form.submit class:"btn btn-success my-2" %>
  </div>
<% end %>

app/views/cellphones/edit.html.erb
<div class="card col-12 col-md-5 mx-auto mb-3">
  <div class="card-header">
    <h4 class="text-center">Editing <%= @cellphone.brandname%> </h4>
  </div>
  <div class="card-body">
    <%= render 'form', cellphone: @cellphone %>
  </div>
  <div class="card-footer d-flex justify-content-around">
    <%= link_to 'Show', @cellphone, class:"btn btn-success" %> |
    <%= link_to 'Back', cellphones_path, class:"btn btn-secondary py-0 px-5" %>
  </div>
</div>

app/views/cellphones/index.html.erb
<div class="row my-5">
  <% @cellphones.each do |cellphone| %>
  <div class="card col-3 mx-auto bg-light">
    <img src="<%= cellphone.image %>" class="w-100 h-50 bg-white">
    <div class="card-body">
      <p>
        <%= cellphone.brandname %>
      </p>
      <p class="card-text">
        <%= cellphone.color %>
      </p>
      <p class="card-text">
        <%= cellphone.memory %>
      </p>
      <p class="card-text">
        <%= cellphone.description %>
      </p>
      <p class="card-text text-danger">
        <%= cellphone.condition %>
      </p>
      <p class="card-text">
        <%= cellphone.location.upcase %>
      </p>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <div class="col-3">
        <%= link_to 'Show', cellphone, class:"btn btn-outline-success px-1 py-0" %>
      </div>
      <div class="col-3">
        <%= link_to 'Edit', edit_cellphone_path(cellphone), class:"btn btn-outline-success px-1 py-0" %>
      </div>
      <div class="col-3">
        <%= link_to 'Destroy', cellphone, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger px-1 py-0" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<%= link_to 'New Cellphone', new_cellphone_path, class:"btn btn-outline-secondary px-1 py-0" %>





<!--
<p id="notice"><%= notice %></p>
<h1>Cellphones</h1>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Brandname</th>
      <th>Color</th>
      <th>Memory</th>
      <th>Description</th>
      <th>Condition</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cellphones.each do |cellphone| %>
      <tr>
        <td><img src="<%= cellphone.image %>" class="w-100"></td>
        <td><%= cellphone.brandname %></td>
        <td><%= cellphone.color %></td>
        <td><%= cellphone.memory %></td>
        <td><%= cellphone.description %></td>
        <td><%= cellphone.condition %></td>
        <td><%= cellphone.location %></td>
        <td><%= link_to 'Show', cellphone %></td>
        <td><%= link_to 'Edit', edit_cellphone_path(cellphone) %></td>
        <td><%= link_to 'Destroy', cellphone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cellphone', new_cellphone_path %>
-->

app/views/cellphones/new.html.erb
<div class="card col-12 col-md-5 mx-auto mb-3">
  <div class="card-header">
    <h4 class="text-center">Create A New Cellphone Entry</h4>
  </div>
  <div class="card-body">
    <%= render 'form', cellphone: @cellphone %>
  </div>
  <div class="card-footer d-flex justify-content-center">
    <%= link_to 'Back', cellphones_path, class:"btn btn-secondary py-0 px-5" %>
  </div>
</div>

app/views/cellphones/show.html.erb
<div class="card col-4 mx-auto">
  <div class="card-header">
    viewing <%= @cellphone.brandname %>
  </div>
  <p>
  <img src="<%= @cellphone.image %>" class="w-100 h-50 mx-auto">
  </p>
  <div class="card-body">
    <p>
      <strong>Brandname:</strong>
      <%= @cellphone.brandname %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @cellphone.description %>
    </p>
    <p>
      <strong>Condition:</strong>
      <%= @cellphone.condition %>
    </p>
    <p>
      <strong>Location:</strong>
      <%= @cellphone.location %>
    </p>
    <p class="text-danger">
      <strong>Price:</strong>
      <%= @cellphone.price %>
    </p>
  </div>
  <div class="card-footer d-flex justify-content-around">
    <%= link_to 'Edit', edit_cellphone_path(@cellphone), class:"btn btn-success py-0" %> |
    <%= link_to 'Back', cellphones_path, class:"btn btn-secondary py-0" %>
  </div>
</div>












<p id="notice"><%= notice %></p>