config/routes.rb
Rails.application.routes.draw do
  resources :home_appliances
  resources :headphones
  resources :laptops
  resources :televisions
  resources :cellphones
  root "home#index"

  get '/home/', to: 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/television.rb
class Television < ApplicationRecord
  mount_uploader :image, FileUploader
end

app/controllers/televisions_controller.rb
class TelevisionsController < ApplicationController
  before_action :set_television, only: %i[ show edit update destroy ]

  # GET /televisions or /televisions.json
  def index
    @televisions = Television.all
  end

  # GET /televisions/1 or /televisions/1.json
  def show
  end

  # GET /televisions/new
  def new
    @television = Television.new
  end

  # GET /televisions/1/edit
  def edit
  end

  # POST /televisions or /televisions.json
  def create
    @television = Television.new(television_params)

    respond_to do |format|
      if @television.save
        format.html { redirect_to @television, notice: "Television was successfully created." }
        format.json { render :show, status: :created, location: @television }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @television.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /televisions/1 or /televisions/1.json
  def update
    respond_to do |format|
      if @television.update(television_params)
        format.html { redirect_to @television, notice: "Television was successfully updated." }
        format.json { render :show, status: :ok, location: @television }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @television.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /televisions/1 or /televisions/1.json
  def destroy
    @television.destroy
    respond_to do |format|
      format.html { redirect_to televisions_url, notice: "Television was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_television
      @television = Television.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def television_params
      params.require(:television).permit(:image, :brandname, :description, :condition, :location, :price)
    end
end

app/helpers/televisions_helper.rb
module TelevisionsHelper
end

app/views/televisions/_form.html.erb
<%= form_with(model: television, local: true) do |form| %>
  <% if television.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(television.errors.count, "error") %> prohibited this television from being saved:</h2>

      <ul>
        <% television.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :brandname %>
    <%= form.text_field :brandname, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class="actions my-3 text-center">
    <%= form.submit %>
  </div>
<% end %>

app/views/televisions/edit.html.erb
<div class="card col-12 col-md-5 mx-auto mb-3">
  <div class="card-header">
    <h4 class="text-center">Editing <%= @television.brandname%> </h4>
  </div>
  <div class="card-body">
    <%= render 'form', television: @television %>
  </div>
  <div class="card-footer d-flex justify-content-around">
    <%= link_to 'Show', @television, class:"btn btn-success py-0 px-5" %> |
    <%= link_to 'Back', televisions_path, class:"btn btn-secondary py-0 px-5" %>
  </div>
</div>

app/views/televisions/index.html.erb
<div class="row mt-5">
  <% @televisions.each do |television| %>
    <div class="card col-3 mx-auto mb-5">
      <img src="<%= television.image %>">
      <div class="card-body">
        <p>
          <%= television.brandname %>
        </p>
        <p>
          <%= television.description %>
        </p>
        <p>
          <%= television.condition %>
        </p>
        <p>
          <%= television.location %>
        </p>
        <p>
          <%= television.price %>
        </p>
      </div>
      <div class="card-footer d-flex justify-content-between">
        <div class="col-3">
          <%= link_to 'Show', television, class:"btn btn-outline-success py-0 px-1" %>
        </div>
        <div class="col-3">
          <%= link_to 'Edit', edit_television_path(television), class:"btn btn-outline-success py-0 px-1" %>
        </div>
        <div class="col-3">
          <%= link_to 'Delete', television, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger py-0 px-1" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= link_to 'New Television', new_television_path, class:"btn btn-outline-secondary py-0 my-2 text-center" %>


<!--
<p id="notice"><%= notice %></p>

<h1>Televisions</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Brandname</th>
      <th>Description</th>
      <th>Condition</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @televisions.each do |television| %>
      <tr>
        <td><img src="<%= television.image %>"></td>
        <td><%= television.brandname %></td>
        <td><%= television.description %></td>
        <td><%= television.condition %></td>
        <td><%= television.location %></td>
        <td><%= link_to 'Show', television %></td>
        <td><%= link_to 'Edit', edit_television_path(television) %></td>
        <td><%= link_to 'Destroy', television, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Television', new_television_path %>

-->

app/views/televisions/new.html.erb
<div class="card col-12 col-md-5 mx-auto mb-3">
  <div class="card-header">
    <h4 class="text-center"> Create New Television Entry</h4>
  </div>
  <div class="card-body">
    <%= render 'form', television: @television %>
  </div>
  <div class="card-footer d-flex justify-content-center">
    <%= link_to 'Back', televisions_path, class:"btn btn-secondary py-0 px-5" %>
  </div>
</div>

app/views/televisions/show.html.erb
<div class="card col-4 mx-auto">
  <div class="card-header">
    viewing <%= @television.brandname %>
  </div>
  <p>
  <img src="<%= @television.image %>" class="w-100 h-50">
  </p>
  <div class="card-body">
    <p>
      <strong>Brandname:</strong>
      <%= @television.brandname %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @television.description %>
    </p>
    <p>
      <strong>Condition:</strong>
      <%= @television.condition %>
    </p>
    <p>
      <strong>Location:</strong>
      <%= @television.location %>
    </p>
    <p class="text-danger">
      <strong>Price:</strong>
      <%= @television.price %>
    </p>
  </div>
  <div class="card-footer d-flex justify-content-around">
    <%= link_to 'Edit', edit_television_path(@television), class:"btn btn-success py-0" %> |
    <%= link_to 'Back', televisions_path, class:"btn btn-secondary py-0" %>
  </div>
</div>




<p id="notice"><%= notice %></p>