config/routes.rb
Rails.application.routes.draw do
  resources :home_appliances
  resources :headphones
  resources :laptops
  resources :televisions
  resources :cellphones
  root "home#index"

  get '/home/', to: 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/laptop.rb
class Laptop < ApplicationRecord
  mount_uploader :image, FileUploader
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  before_action :set_laptop, only: %i[ show edit update destroy ]

  # GET /laptops or /laptops.json
  def index
    @laptops = Laptop.all
  end

  # GET /laptops/1 or /laptops/1.json
  def show
  end

  # GET /laptops/new
  def new
    @laptop = Laptop.new
  end

  # GET /laptops/1/edit
  def edit
  end

  # POST /laptops or /laptops.json
  def create
    @laptop = Laptop.new(laptop_params)

    respond_to do |format|
      if @laptop.save
        format.html { redirect_to @laptop, notice: "Laptop was successfully created." }
        format.json { render :show, status: :created, location: @laptop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptops/1 or /laptops/1.json
  def update
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to @laptop, notice: "Laptop was successfully updated." }
        format.json { render :show, status: :ok, location: @laptop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1 or /laptops/1.json
  def destroy
    @laptop.destroy
    respond_to do |format|
      format.html { redirect_to laptops_url, notice: "Laptop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laptop
      @laptop = Laptop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def laptop_params
      params.require(:laptop).permit(:image, :brandname, :description, :condition, :location, :price)
    end
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/laptops/_form.html.erb
<%= form_with(model: laptop, local: true) do |form| %>
  <% if laptop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(laptop.errors.count, "error") %> prohibited this laptop from being saved:</h2>

      <ul>
        <% laptop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :brandname %>
    <%= form.text_field :brandname, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class="actions text-center my-2">
    <%= form.submit class:"btn btn-success py-0" %>
  </div>
<% end %>

app/views/laptops/edit.html.erb
<div class="card col-12 col-md-5 mx-auto mb-3">
  <div class="card-header">
    <h4 class="text-center">Editing <%= @laptop.brandname%> </h4>
  </div>
  <div class="card-body">
    <%= render 'form', laptop: @laptop %>
  </div>
  <div class="card-footer d-flex justify-content-around">
    <%= link_to 'Show', @laptop, class:"btn btn-success py-0 px-5" %> |
    <%= link_to 'Back', laptops_path, class:"btn btn-secondary py-0 px-5" %>
  </div>
</div>

app/views/laptops/index.html.erb
<div class="row my-3">
  <% @laptops.each do |laptop| %> 
  <div class="card col-3 mx-auto">
    <img src="<%= laptop.image %>">
    <div class="card-body">
      <p class="card-text">
        <%= laptop.brandname %>
      </p>
      <p class="card-text">
        <%= laptop.description %>
      </p>
      <p class="card-text text-danger">
        <%= laptop.condition %>
      </p>
      <p class="card-text">
        <%= laptop.location.upcase %>
      </p>
      <p class="card-text">
        <%= laptop.price %>
      </p>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <div class="col-3">
        <%= link_to 'Show', laptop, class:"btn btn-outline-success btn-sm" %>
      </div>
      <div class="col-3">
        <%= link_to 'Edit', edit_laptop_path(laptop), class:"btn btn-outline-success btn-sm" %>
      </div>
      <div class="col-3">
        <%= link_to 'Destroy', laptop, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %>
      </div>
    </div>
  </div>
  <% end %>
</div>





<!--
<p id="notice"><%= notice %></p>

<h1>Laptops</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Brandname</th>
      <th>Description</th>
      <th>Condition</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laptops.each do |laptop| %>
      <tr>
        <td><img src="<%= laptop.image %>"></td>
        <td><%= laptop.brandname %></td>
        <td><%= laptop.description %></td>
        <td><%= laptop.condition %></td>
        <td><%= laptop.location %></td>
        <td><%= link_to 'Show', laptop %></td>
        <td><%= link_to 'Edit', edit_laptop_path(laptop) %></td>
        <td><%= link_to 'Destroy', laptop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laptop', new_laptop_path %>
-->

app/views/laptops/new.html.erb
<div class="card col-12 col-md-5 mx-auto mb-3">
  <div class="card-header">
    <h4 class="text-center">Create A New Laptop Entry</h4>
  </div>
  <div class="card-body">
    <%= render 'form', laptop: @laptop %>
  </div>
  <div class="card-footer d-flex justify-content-center">
    <%= link_to 'Back', laptops_path, class:"btn btn-secondary py-0 px-5" %>
  </div>
</div>

app/views/laptops/show.html.erb
<div class="card col-4 mx-auto">
  <div class="card-header">
    viewing <%= @laptop.brandname %>
  </div>
  <p>
  <img src="<%= @laptop.image %>" class="w-100 h-50 mx-auto">
  </p>
  <div class="card-body">
    <p>
      <strong>Brandname:</strong>
      <%= @laptop.brandname %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @laptop.description %>
    </p>
    <p>
      <strong>Condition:</strong>
      <%= @laptop.condition %>
    </p>
    <p>
      <strong>Location:</strong>
      <%= @laptop.location %>
    </p>
    <p class="text-danger">
      <strong>Price:</strong>
      <%= @laptop.price %>
    </p>
  </div>
  <div class="card-footer d-flex justify-content-around">
    <%= link_to 'Edit', edit_laptop_path(@laptop), class:"btn btn-success py-0" %> |
    <%= link_to 'Back', laptops_path, class:"btn btn-secondary py-0" %>
  </div>
</div>











<p id="notice"><%= notice %></p>